// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pricing.Infrastructure.Persistence;

#nullable disable

namespace Pricing.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250907180035_AddSeededData")]
    partial class AddSeededData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pricing.Domain.Entities.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinQty")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerUom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PriceLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "EUR",
                            MinQty = 100,
                            PricePerUom = 9.5m,
                            Sku = "ABC123",
                            SupplierId = 1,
                            ValidFrom = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Currency = "USD",
                            MinQty = 50,
                            PricePerUom = 10m,
                            Sku = "ABC123",
                            SupplierId = 2,
                            ValidFrom = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Currency = "EUR",
                            MinQty = 100,
                            PricePerUom = 9.5m,
                            Sku = "ABC123",
                            SupplierId = 3,
                            ValidFrom = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Currency = "EUR",
                            MinQty = 10,
                            PricePerUom = 5.25m,
                            Sku = "XYZ777",
                            SupplierId = 1,
                            ValidFrom = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Currency = "USD",
                            MinQty = 10,
                            PricePerUom = 5.40m,
                            Sku = "XYZ777",
                            SupplierId = 2,
                            ValidFrom = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Pricing.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HazardClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HazardClass = "None",
                            Name = "Product ABC",
                            Sku = "ABC123",
                            Uom = "pcs"
                        },
                        new
                        {
                            Id = 2,
                            HazardClass = "Flammable",
                            Name = "Product XYZ",
                            Sku = "XYZ777",
                            Uom = "pcs"
                        });
                });

            modelBuilder.Entity("Pricing.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Preferred")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Country = "DE",
                            LeadTimeDays = 5,
                            Name = "Supplier A",
                            Preferred = true
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Country = "US",
                            LeadTimeDays = 3,
                            Name = "Supplier B",
                            Preferred = false
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Country = "FR",
                            LeadTimeDays = 4,
                            Name = "Supplier C",
                            Preferred = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
